package com.dicemc.marketplace.util;

public enum CkPktType {
	TEMPCLAIM, EXTEND, CLAIM, OUTPOST, SELL, ABANDON, PUBLIC, ADDMEMBER, REMOVEMEMBER, WL_CHANGE, WL_CLEAR, SUBLET_INTERVAL, SUBLET_PRICE, WL_GUILD_MIN, RENT_START, RENT_EXTEND;
}
